### ISSUE TITLE
Compiling Diamond MinimapIcon 

### ISSUE THREAD

**Issue by Alekhoff** [Xeverous/filter_spirit#20]
**Description**
When compiling a block that has the diamond MinimapIcon, its missing a "d" after compiling
**Steps to reproduce**
<pre>
SetMinimapIcon MinimapIcon(0, white, diamond)
</pre>
**Expected result**
<pre>
MinimapIcon 0 White Diamond
</pre>
**Actual result**
<pre>
MinimapIcon 0 White Diamon
</pre>

**Comment by Xeverous** [comment]
That's a nice typo

https://github.com/Xeverous/filter_spirit/blob/fd405c339086df24a9defb328cfa534be913b31a/src/lib/fs/lang/generation.hpp#L69-L74

**Comment by Xeverous** [comment]
Fixed in 142f9e41f544ac686b668ff473eb93318beebb7a.
