### ISSUE TITLE
Add a condition for ElderMap <Boolean>

### ISSUE THREAD

**Issue by Alekhoff** [Xeverous/filter_spirit#21]
**Description and/or example**
There is already a condition for `ShaperMap <Boolean>`, would be very nice if we could get the same for `ElderMap <Boolean>`

**Comment by Alekhoff** [comment]
Also, same for `BlightedMap <Boolean>`

**Comment by Xeverous** [comment]
Strange, I thought everything was implemented. I know wiki is not up to date, but I scanned all GGG's posts about filters and even made a list of them in `doc/ggg_filters_changelog.md`.

Anyway, done in d52be4f01a68f8f9c070c383c6ac6b8b28616b74.
