### ISSUE TITLE
Adding support for Shaper voice lines 

### ISSUE THREAD

**Issue by Alekhoff** [Xeverous/filter_spirit#33]
Currently filter_spirit does not support the Shaper voice lines, would be nice if they could be added.

| Voice line | Syntax |
|--|--|
| Mirror Of Kalandra | ShMirror |
| Exalted Orb | ShExalted |
| Divine Orb | ShDivine |
|Orb Of Immense Power | ShGeneral |
| Regal Orb | ShRegal |
| Chaos Orb | ShChaos |
| Orb Of Fusing | ShFusing |
| Orb Of Alchemy | ShAlchemy |
| Vaal Orb | ShVaal | 
| Blessed Orb | ShBlessed |

These are all the voice lines I could find with Shaper. 
Used like this in normal filter syntax: 

    PlayAlertSound ShMirror 300
So I assume it would be like this in Filter_Spirit

        SetAlertSound ShMirror 300

Or if stored in a variable:

    $alert_shaper_mirror = ShMirror 300

**Comment by Xeverous** [comment]
Done in 399c3a3e9c6a3d9b90e1675dfb6e6510fff5020b. Should be absolutely free of any bugs. I checked how they work in the client and just like integer sound IDs they can also be Positional and have volume.

**Comment by Xeverous** [comment]
https://www.pathofexile.com/forum/view-thread/1930848

This was the topic that I missed. `ItemFilterAlert11` etc are not implemented but they are the same as sounds `11` to `16` so this is a non-issue. I wonder if anyone ever uses the longer form.
