### ISSUE TITLE
The conditions HasEnchantment is giving error when parsing filterspirit file

### ISSUE THREAD

**Issue by Alekhoff** [Xeverous/filter_spirit#37]
**Description**
Trying to use the HasEnchantment "some enchatment name" in a filterspirit file, but its giving error when parsing, making me belive it might not be supported at this moment? 
**Steps to reproduce**
Try putting this in your filter:

```
AnyEnchantment True {
				Class "Helmets" {
					HasEnchantment "Enchantment Blade Vortex Area Of Effect 2" {
						Set $comp_enchanted_t1
						Show	
					}
				}
			}
```

**Expected result**
Should give a block that highlights that enchant only
**Actual result**
Fails
**Additional context**
(any other info if needed)

**Comment by Xeverous** [comment]
Sorry for missing this issue (I should check mail more often). I'm allocating more time for FS in upcoming weeks, so maybe ... finally I will push out something bigger before another league begins.

I can not reproduce this problem. I think you just might be using an outdated version without the support for `HasEnchantment`. This code works for me without problems (v0.7.0).

**Comment by Alekhoff** [comment]
Yeah, sorry. 
This code works for me as well when I did it again. Must have been doing something wrong in another way, cause I was running (v0.7.0)
